version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  test:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm
          cache-key: "v1-deps-{{ checksum 'pnpm-lock.yaml' }}"
      - run:
          name: Build
          command: pnpm build
          environment:
            TURBO_UI: "false"
      - run:
          name: Test
          command: pnpm test
          environment:
            TURBO_UI: "false"
